sudo: required
services:
  - docker

before_install:
  - docker build -t flowrin13/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run flowrin13/react-test npm test --watchAll=false



