sudo: required
services:
  - docker

before_install:
  - docker build -t flowrin13/react-test -f ./client/Dockerfile.dev ./client #reme

script:
  - docker run flowrin13/react-test npm test

after_success:
  - docker build -t flowrin13/multi-client ./client
  - docker build -t flowrin13/multi-nginx ./nginx
  - docker build -t flowrin13/multi-server ./server
  - docker build -t flowrin13/multi-worker ./worker

  #LOGIN DOCKER HUB
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - docker push flowrin13/multi-client
  - docker push flowrin13/multi-nginx
  - docker push flowrin13/multi-server
  - docker push flowrin13/multi-worker
